import fs from "node:fs/promises";
import os from "node:os";
import { shellSingleQuote } from "./shell-quote";

export interface RunnerOptions {
	pluginVersion: string;
	loginShell: string;
	vaultPath: string;
	logsDir: string;
	locksDir: string;
	extraPath: readonly string[];
	logMaxBytes: number;
}

/**
 * The login shell to run jobs under.
 *
 * This has to be captured by the plugin rather than read inside the runner:
 * cron sets `SHELL=/bin/sh`, so by the time a job is running the user's real
 * shell is no longer discoverable from the environment.
 */
export function detectLoginShell(override?: string | null): string {
	if (override && override.trim() !== "") return override.trim();
	const fromEnv = process.env.SHELL;
	if (fromEnv && fromEnv.trim() !== "") return fromEnv.trim();
	return os.platform() === "darwin" ? "/bin/zsh" : "/bin/bash";
}

/**
 * Builds the wrapper that every cron line and every "Run now" invocation calls.
 *
 * Keeping this in one generated file means a scheduled run and a manual run go
 * through identical code — cwd, environment, locking and logging all included —
 * so a job that works from the command palette also works at 3am.
 */
export function buildRunnerScript(options: RunnerOptions): string {
	const q = shellSingleQuote;
	const pathPrefix = options.extraPath.filter((entry) => entry.trim() !== "").join(":");

	return `#!/bin/sh
# Generated by the Obsidian Cron plugin v${options.pluginVersion}.
# Do not edit: this file is regenerated whenever the plugin loads.
set -u

JOB_ID="\${1:?missing job id}"
SCRIPT="\${2:?missing script path}"

VAULT=${q(options.vaultPath)}
LOGS=${q(options.logsDir)}
LOCKS=${q(options.locksDir)}
LOGIN_SHELL=${q(options.loginShell)}
EXTRA_PATH=${q(pathPrefix)}
MAXBYTES=${q(String(options.logMaxBytes))}

mkdir -p "$LOGS" "$LOCKS" || exit 1
LOG="$LOGS/$JOB_ID.log"
LOCK="$LOCKS/$JOB_ID.lock"
STATUS_FILE="$LOGS/$JOB_ID.status"

# Locking, without flock, which does not exist on macOS.
#
# The pid is written to a private file and that file is then hard-linked into
# place: ln fails when the target exists, so exactly one run can take the lock,
# and the lock is never observable without its pid. Creating the lock first and
# filling in the pid afterwards would leave a window in which a second run sees
# an empty lock, calls it stale, and runs concurrently.
#
# Exit 75 (EX_TEMPFAIL) means "skipped, already running", not a job failure.
CLAIM="$LOCKS/$JOB_ID.$$.claim"
trap 'rm -f "$CLAIM"' EXIT INT TERM HUP
printf '%s\\n' "$$" > "$CLAIM" || exit 1

# mkdir is the fallback for filesystems with no hard links (FAT/exFAT), where
# it is still atomic but cannot publish the lock and the pid in one step.
take_lock() {
	ln "$CLAIM" "$LOCK" 2>/dev/null && return 0
	[ -e "$LOCK" ] && return 1
	mkdir "$LOCK" 2>/dev/null
}

if ! take_lock; then
	HOLDER=$(cat "$LOCK" 2>/dev/null)
	if [ -n "$HOLDER" ] && kill -0 "$HOLDER" 2>/dev/null; then
		exit 75
	fi

	# The holder is gone. Renaming the stale lock aside is itself atomic, so of
	# several runs that all saw it, only one wins the right to clear it.
	STALE="$LOCK.stale.$$"
	mv "$LOCK" "$STALE" 2>/dev/null || exit 75
	if [ "$(cat "$STALE" 2>/dev/null)" != "$HOLDER" ]; then
		# A live run replaced the lock between the read and the rename. Put it
		# back, unless something has taken the lock again in the meantime.
		ln "$STALE" "$LOCK" 2>/dev/null
		rm -rf "$STALE"
		exit 75
	fi
	rm -rf "$STALE"
	take_lock || exit 75
fi
trap 'rm -rf "$LOCK" "$CLAIM"' EXIT INT TERM HUP

# Keep the log from growing without bound inside the vault.
if [ -f "$LOG" ] && [ "$(wc -c < "$LOG")" -gt "$MAXBYTES" ]; then
	tail -c "$((MAXBYTES / 2))" "$LOG" > "$LOG.tmp" && mv "$LOG.tmp" "$LOG"
fi

exec >> "$LOG" 2>&1

cd "$VAULT" || exit 1
printf '\\n===== %s  start %s =====\\n' "$(date '+%Y-%m-%d %H:%M:%S %z')" "$JOB_ID"

if [ -n "$EXTRA_PATH" ]; then
	PATH="$EXTRA_PATH:$PATH"
	export PATH
fi

# The script path travels as an environment variable rather than being spliced
# into the -c string, so no filename can be reinterpreted as shell syntax.
# Note that -l sources .zprofile/.bash_profile but not .zshrc/.bashrc, which
# are interactive-only.
OBSIDIAN_CRON_SCRIPT="$SCRIPT" \\
OBSIDIAN_CRON_JOB_ID="$JOB_ID" \\
OBSIDIAN_VAULT_PATH="$VAULT" \\
	"$LOGIN_SHELL" -l -c 'exec "$OBSIDIAN_CRON_SCRIPT"'
STATUS=$?

printf '===== %s  exit %s =====\\n' "$(date '+%Y-%m-%d %H:%M:%S %z')" "$STATUS"
printf '%s %s\\n' "$(date +%s)" "$STATUS" > "$STATUS_FILE"
exit "$STATUS"
`;
}

/** Writes the runner only when its content changed, and always marks it executable. */
export async function ensureRunnerScript(runnerPath: string, options: RunnerOptions): Promise<void> {
	const desired = buildRunnerScript(options);
	let current: string | null = null;
	try {
		current = await fs.readFile(runnerPath, "utf8");
	} catch {
		current = null;
	}
	if (current !== desired) {
		await fs.writeFile(runnerPath, desired, { mode: 0o755 });
	}
	// chmod unconditionally: the file may predate this version, or have been
	// copied into place by a vault sync that dropped the mode bits.
	await fs.chmod(runnerPath, 0o755);
}
