import fs from "node:fs/promises";
import os from "node:os";
import { shellSingleQuote } from "./shell-quote";

export interface RunnerOptions {
	pluginVersion: string;
	loginShell: string;
	vaultPath: string;
	logsDir: string;
	locksDir: string;
	extraPath: readonly string[];
	logMaxBytes: number;
}

/**
 * The login shell to run jobs under.
 *
 * This has to be captured by the plugin rather than read inside the runner:
 * cron sets `SHELL=/bin/sh`, so by the time a job is running the user's real
 * shell is no longer discoverable from the environment.
 */
export function detectLoginShell(override?: string | null): string {
	if (override && override.trim() !== "") return override.trim();
	const fromEnv = process.env.SHELL;
	if (fromEnv && fromEnv.trim() !== "") return fromEnv.trim();
	return os.platform() === "darwin" ? "/bin/zsh" : "/bin/bash";
}

/**
 * Builds the wrapper that every cron line and every "Run now" invocation calls.
 *
 * Keeping this in one generated file means a scheduled run and a manual run go
 * through identical code — cwd, environment, locking and logging all included —
 * so a job that works from the command palette also works at 3am.
 */
export function buildRunnerScript(options: RunnerOptions): string {
	const q = shellSingleQuote;
	const pathPrefix = options.extraPath.filter((entry) => entry.trim() !== "").join(":");

	return `#!/bin/sh
# Generated by the Obsidian Cron plugin v${options.pluginVersion}.
# Do not edit: this file is regenerated whenever the plugin loads.
set -u

JOB_ID="\${1:?missing job id}"
SCRIPT="\${2:?missing script path}"

VAULT=${q(options.vaultPath)}
LOGS=${q(options.logsDir)}
LOCKS=${q(options.locksDir)}
LOGIN_SHELL=${q(options.loginShell)}
EXTRA_PATH=${q(pathPrefix)}
MAXBYTES=${q(String(options.logMaxBytes))}

mkdir -p "$LOGS" "$LOCKS" || exit 1
LOG="$LOGS/$JOB_ID.log"
LOCK="$LOCKS/$JOB_ID.lock"
STATUS_FILE="$LOGS/$JOB_ID.status"

# mkdir is atomic on every POSIX filesystem; flock does not exist on macOS.
# Exit 75 (EX_TEMPFAIL) means "skipped, already running", not a job failure.
if ! mkdir "$LOCK" 2>/dev/null; then
	if [ -f "$LOCK/pid" ] && kill -0 "$(cat "$LOCK/pid")" 2>/dev/null; then
		exit 75
	fi
	rm -rf "$LOCK"
	mkdir "$LOCK" 2>/dev/null || exit 75
fi
printf '%s\\n' "$$" > "$LOCK/pid"
trap 'rm -rf "$LOCK"' EXIT INT TERM HUP

# Keep the log from growing without bound inside the vault.
if [ -f "$LOG" ] && [ "$(wc -c < "$LOG")" -gt "$MAXBYTES" ]; then
	tail -c "$((MAXBYTES / 2))" "$LOG" > "$LOG.tmp" && mv "$LOG.tmp" "$LOG"
fi

exec >> "$LOG" 2>&1

cd "$VAULT" || exit 1
printf '\\n===== %s  start %s =====\\n' "$(date '+%Y-%m-%d %H:%M:%S %z')" "$JOB_ID"

if [ -n "$EXTRA_PATH" ]; then
	PATH="$EXTRA_PATH:$PATH"
	export PATH
fi

# The script path travels as an environment variable rather than being spliced
# into the -c string, so no filename can be reinterpreted as shell syntax.
# Note that -l sources .zprofile/.bash_profile but not .zshrc/.bashrc, which
# are interactive-only.
OBSIDIAN_CRON_SCRIPT="$SCRIPT" \\
OBSIDIAN_CRON_JOB_ID="$JOB_ID" \\
OBSIDIAN_VAULT_PATH="$VAULT" \\
	"$LOGIN_SHELL" -l -c 'exec "$OBSIDIAN_CRON_SCRIPT"'
STATUS=$?

printf '===== %s  exit %s =====\\n' "$(date '+%Y-%m-%d %H:%M:%S %z')" "$STATUS"
printf '%s %s\\n' "$(date +%s)" "$STATUS" > "$STATUS_FILE"
exit "$STATUS"
`;
}

/** Writes the runner only when its content changed, and always marks it executable. */
export async function ensureRunnerScript(runnerPath: string, options: RunnerOptions): Promise<void> {
	const desired = buildRunnerScript(options);
	let current: string | null = null;
	try {
		current = await fs.readFile(runnerPath, "utf8");
	} catch {
		current = null;
	}
	if (current !== desired) {
		await fs.writeFile(runnerPath, desired, { mode: 0o755 });
	}
	// chmod unconditionally: the file may predate this version, or have been
	// copied into place by a vault sync that dropped the mode bits.
	await fs.chmod(runnerPath, 0o755);
}
